spring:
  application:
    name: tef-austral-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}

auth0:
  audience: ${AUTH0_AUDIENCE}
  domain: ${AUTH0_DOMAIN}
  management:
    client-id: ${AUTH0_MGMT_CLIENT_ID}
    client-secret: ${AUTH0_MGMT_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always