spring:
  application:
    name: tef-austral-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://tef-austral.us.auth0.com/}

auth0:
  audience: ${AUTH0_AUDIENCE:https://tef-austral.com/api}
  domain: ${AUTH0_DOMAIN:tef-austral.us.auth0.com}
  management:
    client-id: ${AUTH0_MGMT_CLIENT_ID}
    client-secret: ${AUTH0_MGMT_CLIENT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always